# SwiftLint Configuration for AIKO iOS Project
# Focus on project files only, exclude dependencies and build artifacts

# Paths to include for linting (only our source files)
included:
  - Sources/
  - Tests/
  - AIKO/

# Paths to exclude from linting  
excluded:
  - .build/
  - .swiftpm/
  - DerivedData/
  - Pods/
  - Package.swift
  - "**/*.generated.swift"
  - "**/Carthage/"
  - "**/checkouts/"
  - "**/Build/"

# Disabled rules for iOS development flexibility
disabled_rules:
  - trailing_comma           # Allow trailing commas for cleaner diffs
  - todo                     # Allow TODOs during development
  - line_length              # More flexible line length for iOS
  - file_length              # Some view controllers can be longer
  - function_body_length     # Some setup functions need more lines
  - type_body_length         # Some SwiftUI views can be complex
  - cyclomatic_complexity    # Some business logic can be complex
  - identifier_name          # Allow shorter names for common patterns (x, y, id)
  - multiple_closures_with_trailing_closure # Allow SwiftUI syntax patterns
  - nesting                  # Allow deeper nesting for SwiftUI views
  - large_tuple              # Allow larger tuples for state management
  - force_try                # Temporarily disable during fixes
  - empty_enum_arguments     # Allow explicit wildcard patterns for clarity

# Rules that are important for iOS quality
opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - strong_iboutlet
  - closure_spacing
  - operator_usage_whitespace
  - return_arrow_whitespace
  - trailing_whitespace
  - vertical_whitespace
  - opening_brace
  - colon
  - comma
  - control_statement

# Custom rule configurations (commented out for disabled rules)
# line_length: 
#   warning: 120
#   error: 200
#   ignores_urls: true
#   ignores_function_declarations: true
#   ignores_comments: true

# function_body_length:
#   warning: 60
#   error: 100

# type_body_length:
#   warning: 300
#   error: 400

# file_length:
#   warning: 500
#   error: 800

# cyclomatic_complexity:
#   warning: 15
#   error: 25

# Naming conventions for iOS (commented out for disabled rule)
# identifier_name:
#   min_length: 2  # Allow 'x', 'y', 'id' etc.
#   max_length: 40
#   excluded:
#     - id
#     - x
#     - y
#     - z
#     - i
#     - j
#     - k

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - ID
    - URL
    - UI

# Reporter type
reporter: "xcode"

# Severity levels - STRICT ENFORCEMENT for TDD workflow
# warning_threshold: 0    # ZERO tolerance - all warnings must be resolved (temporarily disabled)