// Generated by Apple Swift version 6.1.2 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef AIKO_SWIFT_H
#define AIKO_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AIKO",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSEntityDescription;
@class NSManagedObjectContext;
SWIFT_CLASS_NAMED("Acquisition")
@interface Acquisition : NSManagedObject
- (void)awakeFromInsert;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class UploadedFile;
@class NSSet;
@interface Acquisition (SWIFT_EXTENSION(AIKO))
- (void)addUploadedFilesObject:(UploadedFile * _Nonnull)value;
- (void)removeUploadedFilesObject:(UploadedFile * _Nonnull)value;
- (void)addUploadedFiles:(NSSet * _Nonnull)values;
- (void)removeUploadedFiles:(NSSet * _Nonnull)values;
@end

@class GeneratedFile;
@interface Acquisition (SWIFT_EXTENSION(AIKO))
- (void)addGeneratedFilesObject:(GeneratedFile * _Nonnull)value;
- (void)removeGeneratedFilesObject:(GeneratedFile * _Nonnull)value;
- (void)addGeneratedFiles:(NSSet * _Nonnull)values;
- (void)removeGeneratedFiles:(NSSet * _Nonnull)values;
@end

@class AcquisitionDocument;
@interface Acquisition (SWIFT_EXTENSION(AIKO))
- (void)addDocumentsObject:(AcquisitionDocument * _Nonnull)value;
- (void)removeDocumentsObject:(AcquisitionDocument * _Nonnull)value;
- (void)addDocuments:(NSSet * _Nonnull)values;
- (void)removeDocuments:(NSSet * _Nonnull)values;
@end

@class NSUUID;
@class NSString;
@class NSDate;
@class NSData;
@interface Acquisition (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSUUID * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable projectNumber;
@property (nonatomic, copy) NSString * _Nullable requirements;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSDate * _Nullable createdDate;
@property (nonatomic, copy) NSDate * _Nullable lastModifiedDate;
@property (nonatomic, copy) NSData * _Nullable documentChainMetadata;
@property (nonatomic, strong) NSSet * _Nullable documents;
@property (nonatomic, strong) NSSet * _Nullable uploadedFiles;
@property (nonatomic, strong) NSSet * _Nullable generatedFiles;
@end

SWIFT_CLASS_NAMED("AcquisitionDocument")
@interface AcquisitionDocument : NSManagedObject
- (void)awakeFromInsert;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface AcquisitionDocument (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSUUID * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable documentType;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSDate * _Nullable createdDate;
@property (nonatomic, strong) Acquisition * _Nullable acquisition;
@end

SWIFT_CLASS_NAMED("DocumentAttribute")
@interface DocumentAttribute : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("DocumentData")
@interface DocumentData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("GeneratedFile")
@interface GeneratedFile : NSManagedObject
- (void)awakeFromInsert;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface GeneratedFile (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSUUID * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable fileName;
@property (nonatomic, copy) NSData * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable fileType;
@property (nonatomic, copy) NSDate * _Nullable createdDate;
@property (nonatomic, strong) Acquisition * _Nullable acquisition;
@end

SWIFT_CLASS_NAMED("GovernmentFormData")
@interface GovernmentFormData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface GovernmentFormData (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSUUID * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable formType;
@property (nonatomic, copy) NSString * _Nullable formNumber;
@property (nonatomic, copy) NSString * _Nullable revision;
@property (nonatomic, copy) NSData * _Nullable formData;
@property (nonatomic, copy) NSDate * _Nullable createdDate;
@property (nonatomic, copy) NSDate * _Nullable lastModifiedDate;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSData * _Nullable metadata;
@property (nonatomic, strong) Acquisition * _Nullable acquisition;
@end

SWIFT_CLASS_NAMED("MetricComparisonEntity")
@interface MetricComparisonEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class MetricMeasurementEntity;
@class MetricsReportEntity;
@interface MetricComparisonEntity (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSUUID * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) double difference;
@property (nonatomic) double percentageChange;
@property (nonatomic, copy) NSString * _Nullable interpretation;
@property (nonatomic, strong) MetricMeasurementEntity * _Nullable baseline;
@property (nonatomic, strong) MetricMeasurementEntity * _Nullable comparison;
@property (nonatomic, strong) MetricsReportEntity * _Nullable report;
@end

SWIFT_CLASS_NAMED("MetricInsightEntity")
@interface MetricInsightEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface MetricInsightEntity (SWIFT_EXTENSION(AIKO))
- (void)addMeasurementsObject:(MetricMeasurementEntity * _Nonnull)value;
- (void)removeMeasurementsObject:(MetricMeasurementEntity * _Nonnull)value;
- (void)addMeasurements:(NSSet * _Nonnull)values;
- (void)removeMeasurements:(NSSet * _Nonnull)values;
@end

@class MetricsSummaryEntity;
@interface MetricInsightEntity (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSUUID * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable severity;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSData * _Nullable affectedMetricsData;
@property (nonatomic) double confidence;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic, strong) NSSet * _Nullable measurements;
@property (nonatomic, strong) MetricsSummaryEntity * _Nullable summary;
@end

SWIFT_CLASS_NAMED("MetricMeasurementEntity")
@interface MetricMeasurementEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class MetricValueEntity;
@interface MetricMeasurementEntity (SWIFT_EXTENSION(AIKO))
- (void)addMetricValuesObject:(MetricValueEntity * _Nonnull)value;
- (void)removeMetricValuesObject:(MetricValueEntity * _Nonnull)value;
- (void)addMetricValues:(NSSet * _Nonnull)values;
- (void)removeMetricValues:(NSSet * _Nonnull)values;
@end

@interface MetricMeasurementEntity (SWIFT_EXTENSION(AIKO))
- (void)addInsightsObject:(MetricInsightEntity * _Nonnull)value;
- (void)removeInsightsObject:(MetricInsightEntity * _Nonnull)value;
- (void)addInsights:(NSSet * _Nonnull)values;
- (void)removeInsights:(NSSet * _Nonnull)values;
@end

@interface MetricMeasurementEntity (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSUUID * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable metricType;
@property (nonatomic, copy) NSString * _Nullable mopType;
@property (nonatomic, copy) NSString * _Nullable moeType;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic) double aggregatedValue;
@property (nonatomic) double score;
@property (nonatomic, copy) NSData * _Nullable contextData;
@property (nonatomic, strong) NSSet * _Nullable metricValues;
@property (nonatomic, strong) NSSet * _Nullable insights;
@property (nonatomic, strong) MetricsReportEntity * _Nullable report;
@end

SWIFT_CLASS_NAMED("MetricRecommendationEntity")
@interface MetricRecommendationEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface MetricRecommendationEntity (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSUUID * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable priority;
@property (nonatomic, copy) NSString * _Nullable category;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSData * _Nullable expectedImpactData;
@property (nonatomic) NSTimeInterval timeToImpact;
@property (nonatomic) double impactConfidence;
@property (nonatomic, copy) NSData * _Nullable requiredActionsData;
@property (nonatomic, copy) NSData * _Nullable relatedMetricsData;
@property (nonatomic, strong) MetricsSummaryEntity * _Nullable summary;
@end

SWIFT_CLASS_NAMED("MetricTrendEntity")
@interface MetricTrendEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class TrendDataPointEntity;
@interface MetricTrendEntity (SWIFT_EXTENSION(AIKO))
- (void)addTrendDataPointsObject:(TrendDataPointEntity * _Nonnull)value;
- (void)removeTrendDataPointsObject:(TrendDataPointEntity * _Nonnull)value;
- (void)addTrendDataPoints:(NSSet * _Nonnull)values;
- (void)removeTrendDataPoints:(NSSet * _Nonnull)values;
@end

@interface MetricTrendEntity (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSUUID * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable metricName;
@property (nonatomic, copy) NSString * _Nullable direction;
@property (nonatomic) double magnitude;
@property (nonatomic) double significance;
@property (nonatomic, strong) MetricsReportEntity * _Nullable report;
@property (nonatomic, strong) NSSet * _Nullable trendDataPoints;
@end

SWIFT_CLASS_NAMED("MetricValueEntity")
@interface MetricValueEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface MetricValueEntity (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSUUID * _Nullable id;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic) double value;
@property (nonatomic, copy) NSString * _Nullable unit;
@property (nonatomic, copy) NSData * _Nullable metadataData;
@property (nonatomic, strong) MetricMeasurementEntity * _Nullable measurement;
@end

SWIFT_CLASS_NAMED("MetricsReportEntity")
@interface MetricsReportEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface MetricsReportEntity (SWIFT_EXTENSION(AIKO))
- (void)addDetailedMeasurementsObject:(MetricMeasurementEntity * _Nonnull)value;
- (void)removeDetailedMeasurementsObject:(MetricMeasurementEntity * _Nonnull)value;
- (void)addDetailedMeasurements:(NSSet * _Nonnull)values;
- (void)removeDetailedMeasurements:(NSSet * _Nonnull)values;
@end

@interface MetricsReportEntity (SWIFT_EXTENSION(AIKO))
- (void)addTrendsObject:(MetricTrendEntity * _Nonnull)value;
- (void)removeTrendsObject:(MetricTrendEntity * _Nonnull)value;
- (void)addTrends:(NSSet * _Nonnull)values;
- (void)removeTrends:(NSSet * _Nonnull)values;
@end

@interface MetricsReportEntity (SWIFT_EXTENSION(AIKO))
- (void)addComparisonsObject:(MetricComparisonEntity * _Nonnull)value;
- (void)removeComparisonsObject:(MetricComparisonEntity * _Nonnull)value;
- (void)addComparisons:(NSSet * _Nonnull)values;
- (void)removeComparisons:(NSSet * _Nonnull)values;
@end

@interface MetricsReportEntity (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSUUID * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSDate * _Nullable periodStart;
@property (nonatomic, copy) NSDate * _Nullable periodEnd;
@property (nonatomic, copy) NSDate * _Nullable generatedAt;
@property (nonatomic, copy) NSString * _Nullable executiveSummary;
@property (nonatomic, strong) MetricsSummaryEntity * _Nullable summary;
@property (nonatomic, strong) NSSet * _Nullable detailedMeasurements;
@property (nonatomic, strong) NSSet * _Nullable trends;
@property (nonatomic, strong) NSSet * _Nullable comparisons;
@end

SWIFT_CLASS_NAMED("MetricsSummaryEntity")
@interface MetricsSummaryEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface MetricsSummaryEntity (SWIFT_EXTENSION(AIKO))
- (void)addRecommendationsObject:(MetricRecommendationEntity * _Nonnull)value;
- (void)removeRecommendationsObject:(MetricRecommendationEntity * _Nonnull)value;
- (void)addRecommendations:(NSSet * _Nonnull)values;
- (void)removeRecommendations:(NSSet * _Nonnull)values;
@end

@interface MetricsSummaryEntity (SWIFT_EXTENSION(AIKO))
- (void)addInsightsObject:(MetricInsightEntity * _Nonnull)value;
- (void)removeInsightsObject:(MetricInsightEntity * _Nonnull)value;
- (void)addInsights:(NSSet * _Nonnull)values;
- (void)removeInsights:(NSSet * _Nonnull)values;
@end

@interface MetricsSummaryEntity (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSDate * _Nullable periodStart;
@property (nonatomic, copy) NSDate * _Nullable periodEnd;
@property (nonatomic, copy) NSData * _Nullable mopScoresData;
@property (nonatomic, copy) NSData * _Nullable moeScoresData;
@property (nonatomic) double overallMOPScore;
@property (nonatomic) double overallMOEScore;
@property (nonatomic) double combinedScore;
@property (nonatomic, strong) NSSet * _Nullable insights;
@property (nonatomic, strong) NSSet * _Nullable recommendations;
@property (nonatomic, strong) MetricsReportEntity * _Nullable report;
@end

@class NSURLSession;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;
/// URLSession delegate for certificate pinning
SWIFT_CLASS("_TtC4AIKO21PinnedSessionDelegate")
@interface PinnedSessionDelegate : NSObject <NSURLSessionDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)_ didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("TrendDataPointEntity")
@interface TrendDataPointEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface TrendDataPointEntity (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@property (nonatomic) double value;
@property (nonatomic, strong) MetricTrendEntity * _Nullable trend;
@end

SWIFT_CLASS_NAMED("UploadedFile")
@interface UploadedFile : NSManagedObject
- (void)awakeFromInsert;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface UploadedFile (SWIFT_EXTENSION(AIKO))
@property (nonatomic, copy) NSUUID * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable fileName;
@property (nonatomic, copy) NSData * _Nullable data;
@property (nonatomic, copy) NSDate * _Nullable uploadDate;
@property (nonatomic, copy) NSString * _Nullable contentSummary;
@property (nonatomic, strong) Acquisition * _Nullable acquisition;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
